- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule sync --recursive
    - git submodule update # after linking ~/.gitconfig
    - ./macos

- brewfile:
    file: Brewfile

- shell:
    - ./npm
