#!/usr/bin/env bash

mkdir -p ~/.nvm

[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"

nvm install --lts
nvm alias default lts/*

npm install -g \
  now \
  pure-prompt \
  serve \
  trash-cli